"""default is_active=False

Revision ID: b23fbebc1338
Revises: b3814f4036d2
Create Date: 2025-01-05 10:27:38.025246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23fbebc1338'
down_revision: Union[str, None] = 'b3814f4036d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 'is_active',
        server_default=sa.false(),  # Set the default value to False
        existing_type=sa.Boolean(),
        nullable=True  
    )
  
    # ### end Alembic commands ###


def downgrade() -> None:

    op.alter_column(
        'users', 'is_active',
        server_default=sa.true(),  # Revert to True as default
        existing_type=sa.Boolean(),
        nullable=True  
    )

